//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scales.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("scales.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОРОВА
        ///ЛУНА
        ///СОВА
        ///СОБАКА
        ///КОШКА
        ///ЖЕЛЕЗО
        ///ШКАФ
        ///ЗЕМЛЯ
        ///МАРТ
        ///ЛУЖА
        ///ОБЛАКО
        ///РЕКА
        ///ПОМАДА
        ///СТЕКЛО
        ///ХОМЯК
        ///СЛОН
        ///МЫШЬ
        ///ЖИРАФ
        ///ПЛЕНКА
        ///ЛОДКА
        ///ДВОР
        ///ШЕРСТЬ
        ///ПЛАТОК
        ///ЗАБОР
        ///КРУЖКА
        ///ГОРКА
        ///ГОРОД
        ///ДЕРЕВО
        ///ЛОШАДЬ
        ///АЛЬБОМ
        ///АВТО
        ///УТКА
        ///БЮДЖЕТ
        ///БОРОДА
        ///ГРУСТЬ
        ///КОЗА
        ///ГАЗЕТА
        ///ЗАВТРА
        ///РОТА
        ///ХЛЕБ
        ///МАЛИНА
        ///РЕЦЕПТ
        ///БРАТ
        ///СЕСТРА
        ///БЕДА
        ///БАНТ
        ///БОЕЦ
        ///АГЕНТ
        ///АВТОР
        ///ПИЛОТ
        ///КАМЕРА
        ///НИТЬ
        ///СТАНОК
        ///ГРЯЗЬ
        ///СТАКАН
        ///СТЕНА
        ///ОКНО
        ///ГИТАРА
        ///АИСТ
        ///
        ///.
        /// </summary>
        internal static string anagrams_txt {
            get {
                return ResourceManager.GetString("anagrams.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rfnz1 {
            get {
                object obj = ResourceManager.GetObject("rfnz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rfnz2 {
            get {
                object obj = ResourceManager.GetObject("rfnz2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sad {
            get {
                object obj = ResourceManager.GetObject("sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smilepng {
            get {
                object obj = ResourceManager.GetObject("smilepng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
